### ISSUE TITLE
Start Project

### ISSUE THREAD

**Issue by allanbatista** [lautaroangelico/WebEngine-2.0#4]
Hi, i'm got this erro using php7 and php7-fpm.

php info: https://muina.com.br/info.php

includes/config/webengine.json

```
{
    "system_active": true,
    "debug": true,
    "offline_mode": false,
    "website_template": "legendary",
    "maintenance_page": "https:\/\/forum.webenginecms.org\/",
    "server_name": "MuOnline",
    "website_title": "MuOnline SXIII",
    "website_title_alt": "{MODULE_TITLE} - MuOnline SXIII",
    "website_meta_description": "Join MU Online! the free-to-play fantasy RPG based on the legendary Continent of MU! Feel the power of forbidden magic! Explore and fight!",
    "website_meta_keywords": "MU, MU online, Season13, private server, Battle Core, private MU online, free to play, mmorpg, auto play, free rpg, Free2Play, PVP, multi client and jewels, season XIII",
    "website_forum_link": "https:\/\/forum.webenginecms.org\/",
    "SQL_DB_HOST": "xx.xx.xx.xx",
    "SQL_DB_NAME": "MuOnline",
    "SQL_DB_2_NAME": "Me_MuOnline",
    "SQL_DB_USER": "yyy",
    "SQL_DB_PASS": "xxx",
    "SQL_DB_PORT": "1433",
    "SQL_USE_2_DB": true,
    "SQL_PDO_DRIVER": "1",
    "SQL_ENABLE_MD5": false,
    "SQL_TABLE_PREFIX": "dbo",
    "server_files": "IGCN",
    "language_switch_active": false,
    "language_default": "en",
    "language_debug": false,
    "gmark_bin2hex_enable": false,
    "plugins_system_enable": false,
    "ip_block_system_enable": false,
    "username_alphanumeric_check": true,
    "username_min_length": "4",
    "username_max_length": "10",
    "password_min_length": "6",
    "password_max_length": "12",
    "email_max_length": "50",
    "enable_dynamic_module_editor": false,
    "admincp_sidebar_color": "azure",
    "cron_api_enabled": false,
    "cron_api_private_key": "123456"
}
```

Log exception

```

Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/includes/classes/class.database.php:73 Stack trace: #0 /var/www/html/includes/classes/class.database.php(91): database->queryFetch('SELECT * FROM `...', Array) #1 /var/www/html/includes/classes/class.session.php(199): database->queryFetchSingle('SELECT * FROM `...', Array) #2 /var/www/html/includes/classes/class.session.php(61): sessionControl::_sessionInfo('4bvfog4d56r3rid...', 'sessionid') #3 /var/www/html/includes/classes/class.handler.php(386): sessionControl::initSessionControl() #4 /var/www/html/includes/classes/class.handler.php(77): Handler::_handleRequest() #5 /var/www/html/includes/webengine.php(152): Handler::renderTemplate() #6 /var/www/html/index.php(20): include_once('/var/www/html/i...') #7 {main} thrown in /var/www/html/includes/classes/class.database.php on line 73

```

**Comment by allanbatista** [comment]
The problem was resolved install:

`apt-get install php7.0-intl php7.0-sqlite3`
